apiVersion: v1
kind: Service
metadata:
  name: infoge-app-service
spec:
  selector:
    app: infoge-app
  ports:
    - protocol: "TCP"
      name: login
      port: 5000
      targetPort: 5000
    - protocol: "TCP"
      name: app
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: infoge-app
  spec:
    selector:
      matchLabels:
        app: infoge-app
    replicas: 2
    template:
      metadata:
        labels:
          app: infoge-app
      spec:
        containers:
          - name: infoge-app
            image: infoge-app:latest
            imagePullPolicy: Never
            ports:
            - containerPort: 5000
            - containerPort: 8080